// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      //case TargetPlatform.iOS:
      //  return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg204APMA809gSn76eXkB1GbbbKD9UcHY',
    appId: '1:628101566749:web:09183277398a3ba548d1f4',
    messagingSenderId: '628101566749',
    projectId: 'flutter-food-de0e7',
    authDomain: 'flutter-food-de0e7.firebaseapp.com',
    storageBucket: 'flutter-food-de0e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRj2xY5nUYXcG7v41mAk8sWDbz6PCjnIA',
    appId: '1:628101566749:android:8d90aa9773e15c4948d1f4',
    messagingSenderId: '628101566749',
    projectId: 'flutter-food-de0e7',
    storageBucket: 'flutter-food-de0e7.appspot.com',
  );

  /*static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGBNVkNILtkXf9-VuNZZ51IBB18hZngF4',
    appId: '1:157371465900:ios:891709f83ac5347fc99f09',
    messagingSenderId: '157371465900',
    projectId: 'whatsapp-chat-app-id',
    storageBucket: 'whatsapp-chat-app-id.appspot.com',
    iosClientId:
        '157371465900-5tj8kd5bscqbg38bfs30ccsb2972b0ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappChatApp',
  );*/
}
